apiVersion: lb.lbconfig.carlosedp.com/v1
kind: ExternalLoadBalancer
metadata:
  name: externalloadbalancer-master-haproxy-sample
  namespace: lbconfig-operator-system
spec:
  vip: "192.168.1.41"
  type: "master"
  ports:
    - 6443
  monitor:
    path: "/healthz"
    port: 6443
    monitortype: "https"
  provider:
    vendor: HAProxy
    host: "http://127.0.0.1"
    port: 5555
    creds: haproxy-creds
    validatecerts: no
    debug: true
